### ISSUE TITLE
Navigation mal style von Position und distanzen

### ISSUE THREAD

**Issue by b-lack** [b-lack/qgis-gnavs-plugin#2]
![image](https://github.com/b-lack/search-find-qgis-plugin/assets/11278402/f6d48b2a-be8b-447e-bfa3-b4bcd1db2229)

Welche farben willst du für linen und Punkte? @twiebke

**Comment by twiebke** [comment]
Ich hätte gerne rot oder lila für die Punkte. Lili sieht man angeblich auf und in grün am besten und auf Karten sticht es immer schön hervor.
Den Azimut in Gon und umschaltbar in Grad oder beides. So viele Förster nutzen ja gar nicht eine 400 Gon Bussole.
Mehre Punkte auszuwählen und anhand der Daten wählen zu können welchen man zu erst nimmt, ist nett. Bringt aber nur etwas wenn die Auswahl auch in Karte und Anzeige unterscheidbar ist. 
Routenplanung mit Traveling-Salesman machen wir später. Wenn zwei Punkte dann unterscheidbar ansonsten einer.

**Comment by b-lack** [comment]
Die Punkte sind (aktuell) nicht in meinem Einflussgebiet. Es können ja irgendwelche Punkte auf irgendwelchen Layerns sein. Sie sind gelb, weil das default von QGIS die Farbe ausgewählter Punkte ist.

Gon <-> Rad <-> Grad würde ganz nach hinten schieben. Das ist ja ganz unabhängig von Funktion.

Mehre Punkte auszuwählen: Das lasse ich dich erstmal so testen.
