### ISSUE TITLE
probleme mit internem GNSS

### ISSUE THREAD

**Issue by twiebke** [b-lack/qgis-gnavs-plugin#20]
Bei internem gnss scheint es an einigen Geräten eine mehr oder weniger korrekte Position aber keine Daten zur Anzahl der Satelliten und dop zu geben. Die Messung scheint ewig zu laufen unabhängig von der Anzahl eingestellter Messungen. Ein Klick auf "Add to Map" erzeugt einen Temporärlayer mit Punkten bei denen Unklar ist wie die erzeugt wurden.

**Comment by b-lack** [comment]
Das ist richtig. Interne oft A-GPS geben diese Daten nicht aus, bzw. diese kommen nicht an. Können sie auch nicht, weil sie eventuell nicht über GPS sondern das Mobilfunk oder W-Lan/Provider errechnet werden. Das lässt sich ja aus den aggregierten Daten ablesen.

Die Messung läuft unbegrenzt. Wir hatten damals gesagt, dass man die Messung vorzeitig abbrechen können muss "add to map" aber auch beliebig lang machen kann um das Ergebnis zu verbessern.

Wieso ist das unklar? Meinst du wir sollten die Einstellungen des Users mitspeichern? Oder worauf willst du damit hinweisen?

**Comment by b-lack** [comment]
In der nächsten Version gibt es eine Progress-Bar, die in % angibt, wie weit man ist...aber keine Restriktion, dass man sich daran halten muss.

**Comment by twiebke** [comment]
Es ist unklar woher die Positionen und damit woher die Mittlungen kommen. Die Mittelungen können dann auch nicht sinnvoll erfolgen weil keine Qualitätsparameter vorliegen. Im aktuellen Fall keine Anzahl von Satelliten und DOP Werte. Nach #4 sollte dann eine Warnmeldung: 

> "Die Qualitätsparameter sind so schlecht, dass auf eine Messung verzichtet oder durch die Einmessung von mindestens drei` Hilfspunkten mit Azimut und Distanz für eine anschließende Fehlerberrechnung und -ausgleichsrechnung erfolgen sollte."

    PDOP > 6
    Precision aus NMEA > 2 m
    Streuung der Koordinaten der Auswahlmessungen > 2 m
    Anzahl der Satelliten < 6

erfolgen.

Die Möglichkeit bei Endlosmessung bei schlechter Qualität ist eine Zusatzfunktion die dann auch eine Möglichkeit des Abbruches bedarf. Es darf aber nicht sein, dass man eine Anzahl von zu berücksichtigenden Messungen einstellt und das Plugin trotzdem endlos misst.

**Comment by b-lack** [comment]
Sehe ich und ist vorhanden. Ich hatte nur angenommen und angemerkt, dass die Warnmeldungen sehr LFB spezifisch sind und meiner Meinung nach im FIM-Plugin auftauchen sollten und nicht im GNAVS-Plugin. Aber ich baue es gerne hier ein.
