### ISSUE TITLE
Einmessung mit dem FIM - Plugin und dem GNVAS - Plugin

### ISSUE THREAD

**Issue by b-lack** [b-lack/qgis-gnavs-plugin#27]
Bei der Einmessung sind mir folgende Dinge aufgefallen:

FIM - Plugin:

Mit einem 1 Hz Empfänger dauert die Messung ca. 30s (sollte Theoretisch min. 100s dauern)
Mit einer Externe Antenne (20 Hz), dauert die Messung 40s.
Das "Precision"-Feld bleibt wären der Messung grau

GNVAS Plugin:

Mit einem 1 Hz Empfänger dauert die Messung ca. 50s.
Mit einer Externe Antenne (20 Hz), dauert die Messung 55s.
Das "Precision"-Feld funktioniert Problemlos

by @RicRat

**Comment by b-lack** [comment]
moved here from https://github.com/b-lack/qgis-fim-plugin/issues/66

**Comment by RicRat** [comment]
Ich habe mir die Daten der Einmessung nun genauer angeschaut, in dem ich die Daten aus der Spalte "raw" exportiert habe.
Um es anschaulicher zu gestalten, habe ich es mit Excel in Zeilen und Spalten neu geordnet.

Die Einmessung habe ich auf drei verschiedenen Arten durchgeführt:
 + externe Antenne per USB ohne RTK
 + externe Antenne per USB mit RTK
 + externe Antenne per Bluetooth
 
 Hier ein Ausschnitt der ersten 50 von 100 Messungen mit der Antenne ohne RTK:
 
latitude | longitude
-- | --
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385614999900 | 11050296081666600
50971385425 | 11050295989999900
50971385425 | 11050295989999900
5097138516500000 | 11050295881666600
5097138516500000 | 11050295881666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
5097138481166660 | 11050295856666600
50971384455 | 11050295864999900
50971384455 | 11050295864999900

Bei allen Messungen sehen die Daten ähnlich aus.

Sollten sich die Koordinaten nicht bei jeder Messung etwas unterscheiden?

 Hier noch die Daten als CSV:
 
[ppm10xx.CSV](https://github.com/b-lack/qgis-gnavs-plugin/files/14081855/ppm10xx.CSV)
[ppm10xx+RTK.CSV](https://github.com/b-lack/qgis-gnavs-plugin/files/14081917/ppm10xx%2BRTK.CSV)
[Bluetooth.CSV](https://github.com/b-lack/qgis-gnavs-plugin/files/14081920/Bluetooth.CSV)

**Comment by b-lack** [comment]
Danke @RicRat für die Bereitstellung deiner Messergebnisse.

Messwerte werden nicht nur empfangen und gespeichert, wenn neue Koordinaten verfügbar sind sondern auch wenn sich z.B. die Qualität, die Anzahl der Satelliten ändert. Das lässt sich am Timestamp und (meist) der Spalte "Qualityindicator" ablesen.

Man könnte zur "Problemlösung" vorschlagen, dass nur neue Koordinatenpaare gespeichert werden. Das könnte jedoch bei ungenauen GNSS-Sensoren dazu führen, dass die Einmessung niemals endet, da sich die Koordinaten aufgrund der Ungenauigkeit nie ändern?! @twiebke

**Comment by RicRat** [comment]
Wir haben bei der Inventur von Thüringen Forst ein Plugin verwendet das in diese Weise funktioniert hat. Also das nur bei einer Änderung der aktuellen Koordinaten diese auch für die Einmessung genommen werden.

Das hat auch mit dem internen Empfänger  ganz gut funktioniert.

**Comment by b-lack** [comment]
Technisch kein Problem: Es ist nur abzustimmen, da es Auswirkungen auf die Qualität und Weiterverarbeitung der Daten hat.

**Comment by b-lack** [comment]
In der neuen/aktuellen Version 1.0.10 werden nur Koordinaten gespeichert, die sich von den vorherigen unterscheiden
