### ISSUE TITLE
Funktionalität: Speicherung

### ISSUE THREAD

**Issue by twiebke** [b-lack/qgis-gnavs-plugin#3]
Zur jeder Punktspeicherung soll der ermittelte Punkt und mindestens:
- [x] die durchschnittliche Anzahl der Satelliten
- [x] die durchschnittliche pdop
- [x] die durchschnittliche hdop
- [x] die durchschnittliche vdop
- [x] Beginn der Messung - datetime
- [x] Ende der Messung - datetime
- [x] Gesamtanzahl der Messungen
- [x] Anteil der Messungen zur Koordinatenberechnung
- [x] die Koordinate aus mean der Messungen als Zahl
- [x] die Koordinate aus median der Messungen als Zahl
- [x] Streuung der Werte
- [x] das Gerät
- [x] der Punktname
- [x] Bemerkungen
gespeichert werden.

Dafür ist im Plugin ein Dialog zur Auswahl des Speicherortes vorzusehen und die Daten als Geopackagelayer 'gnss-points' im crs 4326 zu speichern.

**Comment by b-lack** [comment]
![image](https://github.com/b-lack/qgis-gnavs-plugin/assets/11278402/d178173b-e2bd-4b08-8783-0ffaaa1b1db3)
