### ISSUE TITLE
Funktionalität Punktmittelung

### ISSUE THREAD

**Issue by twiebke** [b-lack/qgis-gnavs-plugin#4]
Die zu speichernden Punkte sollen aus einer Vielzahl von Messungen gemittelt werden. Die Mittlung soll  wahlweise über mean oder median aus einem zu wählenden Anteil der Messungen erfolgen. Nach der Messung ist die Streuung der Messwerte anzuzeigen.

Im Plugin ist deshalb ein Dialog zur
- [x] Auswahl oder Eintragung der vorzunehmenden Messungen z.B. 1000
- [x] Auswahl oder Eintragung des Anteiles der für die Mittelung zu verwendenden Messungen z.B. 70 %
- [x] Auswahl der Qualitätskriterien default ist:
       1. Messmodi - fix vor float
       2. PDOP
       3. HDOP
       4. Precision - je kleiner je besser
       5. Anzahl der Satelliten - Messungen mit geringerem Anteil werden nicht berücksichtigt
- [x] Auswahl mean oder median
vorzusehen.

Nach Abschluss der Messungen ist die Streuung der gemittelten Werte anzuzeigen und dem Nutzer die Möglichkeit zur Punktgenierung aus mean oder median zu geben.
Streuung und Koordinaten aus mean und median werden im layer als Zahlenwert gespeichert.

**Comment by b-lack** [comment]
@twiebke zu: "Auswahl oder Eintragung der vorzunehmenden Messungen z.B. 1000" 

Als freie Eingabe oder Dropdown:

- 1
- 10
- 100
- 500
- 1000

**Comment by twiebke** [comment]
Eigentlich ist das ja eher eine ux-Frage. Logisch sollte für die Eingabe der Messungen 0-10 nicht darüber alles möglich sein. Bei Zahleneingabe würde immer eine Tastatur benötigt weshalb ein dropdown sinnvoll erscheint. Die Auswahl sollte 
- 10
- 20
- 50
- 100
- 500
- 1000
sein. 10 bis 50 sind aber schon arge Kompromisse um eine Speicherung mit langsamen Geräten zu ermöglichen. 100 sollte Standard sein.

Für die Auswahl des Anteils der zu berücksichtigen Punkte ebenfalls ein Dropdown mit folgender Einteilung:
- 100
- 80
- 90
- 70
weiter runter sollten wir nicht gehen, ich glaube dann lässt sich nicht mehr sinnvoll eine Auswahl treffen.

**Comment by b-lack** [comment]
@twiebke Welche Variablen meinst du genau mit:

1. Messmodi - fix vor float
2. Precision 

Siehe: https://api.qgis.org/api/classQgsGpsInformation.html#ab8f31e6ab3dfeb6ac04a872d17eac002

**Comment by b-lack** [comment]
Als Ergebnisse der Messungen gebe ich jetzt aus:

nach Auswahl: mean oder median und Standardabweichung für folgende Werte:

- latitude
- longitude
- elevation
- pdop
- vdop
- hdop
- satellitesUsed

@twiebke Brauchst du noch andere Werte oder reicht das?

**Comment by twiebke** [comment]
Zur Frage davor zu fix vor float hatte ich doch schon geantwortet, oder nicht? Dss sollte aus "qualityDescription()" Zeile 86 in https://api.qgis.org/api/qgsgpsinformation_8cpp_source.html
Fixed RTK vor Float RTK vor DGPS vor Autonomous.

Die Werte sind OK, im Augenblick sehe ich nicht, dass man noch mehr braucht. Daneben noch startzeit und endzeit, jeweils mit Datum.

Die Auswahl ob mean oder median ist eine Methode Ausreißer zu eliminieren.

Das Problem ist, dass man sinnvoll erst nach der Messung und Analyse der Standardabweichung für mean oder median entscheiden kann. Deshalb sollte für lat und lon immer mean und median berechnet werden. Wir brauchen auch nur für diese Werte die Standardabweichung. 
Für elevation
pdop
vdop
hdop
satellitesUsed
reicht der mean.

Wir speichern die Punktgeometrie auf Basis von mean oder median. Dafür müssen wir den Anwendern irgendwie die Möglichkeit geben sinnvoll zu wählen. In den Attributdaten sollte lat_mean und lon_mean sowie lat_median und lon_median sowie jeweils die Standardabweichung gespeichert werden.

Die Entscheidung, ob man den Mittelwert (mean) oder den Median verwendet, hängt von der Verteilung der Daten und dem Vorhandensein von Ausreißern ab. Der Mittelwert ist anfälliger für Ausreißer, während der Median robuster gegenüber extremen Werten ist.
Wenn die Daten normalverteilt sind und keine Ausreißer vorhanden sind, kann der Mittelwert verwendet werden. Wenn die Daten jedoch eine schiefe Verteilung aufweisen oder Ausreißer enthalten, ist der Median eine bessere Wahl. Bei einer hohen Standardabweichung kann es sinnvoll sein, den Median zu verwenden.
Daneben könnte man noch die Verwendung folgender Methoden prüfen: 

- den Interquartilsabstand analysieren: Bei dieser Methode wird der Interquartilsabstand (IQR) berechnet, der den Bereich zwischen dem ersten (Q1) und dem dritten Quartil (Q3) abdeckt. Datenpunkte, die außerhalb des Bereichs Q1 - 1,5IQR und Q3 + 1,5IQR liegen, gelten als Ausreißer
- der Z-Score-Methode: https://statistikgrundlagen.de/ebook/chapter/z-standardisierung/
- Tukey's Fences -  ähnlich wie IQR-Abstand, verwendet jedoch andere Schwellenwerte (z. B. 2,2*IQR) für die Identifizierung von Ausreißern
- oder wir nehmen noch ml rein, z.B. Isolation Forest

Das ist aber alles zusätzliche Rechenzeit zu lasten der Zeit und des Akkus. Dadurch, dass wir schon die Messungen mit den schlechten Werten rausschmeißen und die Geometrieerstellung aus mean oder median entsprechend der Streuung anbieten, sollten wir vorerst genau genug sein. Zu diskutieren wäre ob wir die Rohdaten der Messungen nicht separat speichern um ein Postprossessing zu ermöglichen.

**Comment by b-lack** [comment]
Precision ist meines Wissens weder Teil von NMEA noch QGIS
