### ISSUE TITLE
Funktionalität Navigation

### ISSUE THREAD

**Issue by twiebke** [b-lack/qgis-gnavs-plugin#5]
Das Plugin soll die Möglichkeit einer Navigation zu einem ausgewählten Punkt bieten. Wenn der Nutzer einen Punkt in qgis selektiert und das plugin öffnet soll die Distanz in cm oder in m mit zwei Nachkommastellen und die Richtung in Grad und / Gon angezeigt werden.

Im ersten Release soll nichts angezeigt werden, wenn mehr als ein Punkt selektiert wurde. 

In nachfolgenden Versionen sollen die Werte für mehrere Punkte angezeigt werden. Dabei ist in der Anzeige der Punkt auf den sich die Werte beziehen zu integrieren.

In nachfolgenden Versionen soll die Navigation über im Projekt vorhandene Layer, z.B. Forstwege integriert werden. Wenn der Abstand zum Weg > 20 m wieder Luftlinie.

Die Abstands- und Richtungswerte (Luftlinie) sollen auch in nachfolgenden Versionen innerhalb der Funktionalität immer angezeigt werden.

**Comment by b-lack** [comment]
Kann für eine nächste Version wieder geöffnet werden.
