### ISSUE TITLE
Warnmeldung bei schlechter Qualität

### ISSUE THREAD

**Issue by twiebke** [b-lack/qgis-gnavs-plugin#7]
Das Plugin sollte Warnmeldungen zur Qualiät darstellen. Sinnvoll auch in Kombination mit einer Ampelfarbe.
Bei folgenden Werten sollte eine Textmeldung 
"Die Qualitätsparameter sind so schlecht, dass auf eine Messung verzichtet oder durch die Einmessung von mindestens drei Hilfspunkten mit Azimut und Distanz für eine anschließende Fehlerberrechnung und -ausgleichsrechnung erfolgen sollte."
- PDOP > 6
- Precision aus NMEA > 2 m
- Streuung der Koordinaten der Auswahlmessungen > 2 m
- Anzahl der Satelliten < 6

**Comment by b-lack** [comment]
Hier brauche ich mehr Infos:

Grün, wenn alle werte überschritten werden.
Gelb, wenn einige Werte überschritten sind, andere unterschritten?
Rot, wenn alles drunter ist?

Wäre auch schön, wenn die Werte dokumentiert würden. Schließlich wollen wir keine Nutzer ausschließen, die einen anderen Qualitätsanspruch haben.

**Comment by twiebke** [comment]
# Vorschlag - erste Version - irgendein Farbindikator 
## Grün
- fix und
- PDOP < 2 und
- Precision aus NMEA < 1 m und
- Anzahl der Satelliten > 10 
## Gelb
- float und
- PDOP > 2 < 6 oder
- Precision aus NMEA > 1 m < 2 m oder
- Anzahl der Satelliten > 6 < 10 
## Rot
- float, manual und
- PDOP > 6 oder
- Precision aus NMEA >  2 m oder
- Anzahl der Satelliten =< 6 

Eine Dokumentation braucht es sicher, eine weitere Anzeige erachte ich als unnötig. Die Werte können so auch in der Werkzeugleiste GPS-Information ausgelesen werden. Es geht hier nur um eine Indikatordarstellung.

Ab den hier beschriebenen Werten für Rot reden wir nicht mehr von Qualitätsansprüchen sondern vom Raten.

Oben vorgesehener Text ist erst nach Abschluss von 100 Messungen und den entsprechenden Berechnungen möglich. Der Nutzer soll eine Information erhalten wenn die Messungen höchstwahrscheinlich nicht verwendbar sind. Die farblichen Indikatoren davor geben einen Hinweis ob man es trotzdem versuchen könnte.

**Comment by b-lack** [comment]
@twiebke uns das soll wirklich ins GNSS- Plugin? Meiner Meinung nach macht das im Formular und dem Netzausgleichsplugin Sinn.

**Comment by b-lack** [comment]
Precision ist meines Wissens weder Teil von NMEA noch QGIS

## Grün
gpsInfo.qualityIndicator == 'Fixed RTK' and PDOP < 2 and satelliteCount   >= 10

## Gelb
gpsInfo.qualityIndicator == 'Float RTK' and PDOP > 2 < 6 and satelliteCount  > 6 and satelliteCount  < 10

## Rot
ELSE

**Comment by twiebke** [comment]
Sie nennen das accuracy. Sollte in GFA - GNSS Fix Accuracy and Integrity bei NMEA und als hacc und vacc ab Zeile 108 in https://api.qgis.org/api/qgsgpsinformation_8h_source.html

Da mir aber nicht klar ist, wie die das berechnen, erachte ich das eher als informativ. 

Wir probieren das erstmal mit der Farbindikation. Ich befürchte aber, dass das zu einiger Verunsicherung führt weil wir jenseits von RTK immer Rot haben werden. 

Vielleicht sollten wir noch Orange einführen mit
gpsInfo.qualityIndicator == 'Autonomous' and PDOP > 2 < 6 and satelliteCount > 6 and satelliteCount < 10

**Comment by b-lack** [comment]
Ich habe es jetzt so im GNAVS-Plugin umgesetzt. Dort würde ich es aber gar nicht anzeigen, sondern nur im FIM-Plugin.

def getColor(self, gpsInfo):
        """Returns the color of the indicator"""

        if gpsInfo is None or gpsInfo.latitude is None or gpsInfo.longitude is None:
            return 'red'
        elif str(gpsInfo.qualityIndicator) == 'GpsQualityIndicator.RTK' and gpsInfo.pdop < 2 and gpsInfo.satellitesUsed >= 10:
            return 'green'
        elif str(gpsInfo.qualityIndicator) == 'GpsQualityIndicator.FloatRTK' and gpsInfo.pdop < 6 and gpsInfo.satellitesUsed >= 6:
            return 'yellow'
        elif str(gpsInfo.qualityIndicator) == 'GpsQualityIndicator.GPS' and gpsInfo.pdop < 6 and gpsInfo.satellitesUsed >= 6:
            return 'orange'
        else:
            return 'red'

**Comment by twiebke** [comment]
Im FIM ist das nett aber nicht so nötig wie im gnavs. Im FIM haben wir immer noch zwei Baumplotts um die aktuelle Position wiederzufinden. Bei der Erfassung von Punkten nach GNSS braucht der Anwender Hinweise zur Sicherheit der Messung. Die Umsetzung ist elementar für gnavs.
