### ISSUE TITLE
Aufwandsprüfung der Speicherung der Rohdaten

### ISSUE THREAD

**Issue by twiebke** [b-lack/qgis-gnavs-plugin#8]
Entsprechend der Anforderungen aus #4 soll geprüft werden die Rohdaten der Messungen separat zu speichern um ein Postprossessing zu ermöglichen.

Würde bedeuten, dass es noch eines weiteren Dialoges "Willst Du die Messdaten speichern" und eines Dialoges zur Wahl des Speicherortes gibt. Gespeichert wird dann die ID des zu erstellenden Punktes und alle Einzelmessungen inklusive des Messzeitpunktes also eine Sammlung von Datensätzen mit:
- punkt_id - identisch zur ID im Geometrielayer
- Messungsid - fortlaufende Nummer
- latitude
- longitude
- elevation
- pdop
- vdop
- hdop
- satellitesUsed
- timestamp

**Comment by b-lack** [comment]
Die Umsetzung würde etwa einen tag dauern.

Weniger fehleranfälliger und kostengünstiger wäre es, den Nutzer entscheiden zu lassen (Settings), ob die Rohdaten dem eh schon zu speichernden Punkt hinzugefügt werden sollen.

**Comment by twiebke** [comment]
Der Punkt wird in einem geopackage-layer gespeichert, die Messwerte müssten in einen anderen Layer und eindeutig zuordenbar sein. Messwerte im selben Layer ohne Geometrie würde auch gehen,  die Zuordnung könnte man auch hier über eine ID machen. Damit würden die Daten in dem Layer aber sehr unübersichtlich und wir trennen Rohdaten nicht von verarbeiteten Daten.

Die Rohdaten liegen ja schon vor, die Listen müssten mit der id in einen layer geschrieben werden.

**Comment by b-lack** [comment]
Wenn du es so möchtest, dann wäre das doch ein super Feature für eine kommende Version des Plugins.

**Comment by b-lack** [comment]
@twiebke 
ZU: Messungsid - fortlaufende Nummer
Reicht hier die FeatureId? Wenn nicht: Wie soll eine fortlaufende Nummer aussehen/generiert werden?

ZU: punkt_id - identisch zur ID im Geometrielayer
Ist das ein Attribut eines Punktes (von einem Layer in Qgis Instanz), der innerhalb eines definierten Radius liegt? Wie groß soll der Radius sein? Nach welchen Attributnamen soll ich suchen?
